name: ee_employee
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI dan state
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

  # Lokasi dan GPS
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # Penyimpanan lokal & utilitas
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  path_provider: ^2.1.5
  file_picker: ^10.3.3
  file_saver: ^0.3.1
  open_filex: ^4.7.0
  url_launcher: ^6.3.2

  # HTTP dan API
  http: ^1.5.0

  # Gambar & foto
  image_picker: ^1.2.0
  image: ^4.5.4

  # Share/export
  share_plus: ^10.0.2
  syncfusion_flutter_xlsio: ^31.1.19
  onesignal_flutter: ^5.3.4
  firebase_core: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/logoapp.png
    - assets/logoapp2.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logoapp2.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logoapp2.png"
